package grafana:plugins@0.1.0;

interface query-data {
    use types.{plugin-context, query-data-request, query-data-response};

    record error {
        message: string,
    }

    resource data-server {
        constructor(plugin-context: plugin-context);
        query-data: func(request: query-data-request) -> result<query-data-response, error>;
    }
}

world backend {
    export query-data;
}
